@color 74
@mode con cols=1000 lines=1000
@echo "                                                                                                   "
@echo "                                                                                                   "
@echo "     H           H              A              PPPPPPPPP       PPPPPPPPP     Y         Y           "
@echo "     H           H             A A             P        P      P        P     Y       Y            "
@echo "     H           H            A   A            P         P     P         P     Y     Y             "
@echo "     H           H           A     A           P         P     P         P      Y   Y              "
@echo "     H           H          A       A          P        P      P        P        Y Y               "
@echo "     HHHHHHHHHHHHH         AAAAAAAAAAA         PPPPPPPPP       PPPPPPPPP          Y                "
@echo "     H           H        A           A        P               P                  Y                "
@echo "     H           H       A             A       P               P                  Y                "
@echo "     H           H      A               A      P               P                  Y                "
@echo "     H           H     A                 A     P               P                  Y                "
@echo "     H           H    A                   A    P               P                  Y                "
@echo "                                                                                                   "
@echo "                                                                                                   "
@echo "                                                                                                   "
@echo "                                                                                                   "
@echo "     NN          N    EEEEEEEEEEEEEEE    W         W         W                                     "
@echo "     N N         N    E                   W       WWW       W                                      "
@echo "     N  N        N    E                   W       W W       W                                      "
@echo "     N   N       N    E                    W     W   W     W                                       "
@echo "     N    N      N    E                    W     W   W     W                                       "
@echo "     N     N     N    EEEEEEEEEEEEEEE       W   W     W   W                                        "
@echo "     N      N    N    E                     W   W     W   W                                        "
@echo "     N       N   N    E                      W W       W W                                         "
@echo "     N        N  N    E                      W W       W W                                         "
@echo "     N         N N    E                       W         W                                          "
@echo "     N          NN    EEEEEEEEEEEEEEE         W         W                                          "
@echo "                                                                                                   "
@echo "                                                                                                   "
@echo "                                                                                                   "
@echo "                                                                                                   "
@echo "                                                                                                   "
@echo "     Y         Y      EEEEEEEEEEE             A              RRRRRRRR          |                   "
@echo "      Y       Y       E                      A A             R       R         |                   "
@echo "       Y     Y        E                     A   A            R        R        |                   "
@echo "        Y   Y         E                    A     A           R        R        |                   "
@echo "         Y Y          E                   A       A          R       R         |                   "
@echo "          Y           EEEEEEEEEEE        AAAAAAAAAAA         RRRRRRRR          |                   "
@echo "          Y           E                 A           A        R R               |                   "
@echo "          Y           E                A             A       R  RR             |                   "
@echo "          Y           E               A               A      R    RR           |                   "
@echo "          Y           E              A                 A     R      RR                             "
@echo "          Y           EEEEEEEEEEE   A                   A    R        RR       .                   "
@echo "                                                                                                   "
@echo "                                                                                                   "
@echo "                                                                                                   "
@echo "                                                                                                   "
@pause